jobs:
  build:
    docker:
      - image: cimg/rust:latest
    
    working_directory: ~/quicktest_folder

    steps:
      - checkout
      - run: cargo build
      - run: cargo clippy -- -D warnings
      - run: cargo test tle_subcommand -- --test-threads 1
      - run: cargo test cmp_subcommand -- --test-threads 1
      - run: cargo test check_subcommand -- --test-threads 1
      - run: cargo test run_subcommand -- --test-threads 1
