jobs:
  build:
    docker:
      - image: cimg/rust:1.52.1
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: cargo test tle_subcommand -- --test-threads 1
      - run: cargo test cmp_subcommand -- --test-threads 1
      - run: cargo test check_subcommand -- --test-threads 1
