jobs:
  build:
    docker:
      - image: cimg/rust:1.58.0
    
    working_directory: ~/quicktest_folder

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install default-jdk # Install java
      # - run: wget https://dl.google.com/go/go1.18.linux-amd64.tar.gz # Install Go
      # - run: sudo tar -xvf go1.18.linux-amd64.tar.gz
      # - run: sudo mv go /usr/local
      # - run: sudo ln -s /usr/local/go/bin/* /usr/bin
      # - run: rm go1.18.linux-amd64.tar.gz
      - run: curl -s https://get.sdkman.io | bash # install Kotlin
      - run: source "$HOME/.sdkman/bin/sdkman-init.sh"
      - run: ls ~/ -al
      - run: source ~/.bashrc
      - run: source ~/.zshrc
      - run: sdk version
      # - run: cargo build
      # - run: cargo clippy -- -D warnings
      # - run: ./target/debug/quicktest setup config --label="Language::Python.PROGRAM" --value="python3"
      # - run: cargo test cmp_subcommand -- --test-threads 1
      # - run: cargo test stress_subcommand -- --test-threads 1
      # - run: cargo test check_subcommand -- --test-threads 1
      # - run: cargo test output_subcommand -- --test-threads 1
      # - run: cargo test setup_subcommand -- --test-threads 1