name: MacOS Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    name: Build and Run test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          rustc: 1.64
          cargo: 1.64
          target: x86_64-apple-darwin
          components: rustfmt, clippy
      
      - name: Install C/C++
        run: brew install gcc
      
      - name: Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      
      - name: Setup rust version
        run: rustup target list

      - name: Setup C++
        run: alias g++='g++-12'
      
      - name: Setup C
        run: alias gcc='gcc-12'
      
      - shell: bash
        run: |
          rc=~/.bashrc
          echo 'shopt -s expand_aliases' > $rc
          echo 'alias g++="g++-12"' >> $rc
          echo 'alias gcc="gcc-12"' >> $rc

      - shell: bash
        run: source ~/.bashrc
      
      - name: C/C++ version
        run: |
          gcc --version
          g++ --version

      - name: Cargo Version
        run: cargo --version
      
      - name: Cargo Clippy Version
        run: cargo clippy --version
      
      - name: Rustc Version
        run: rustc --version

      - name: Build
        run: cargo build

      - name: Clippy
        run: cargo clippy

      - name: Setup 'python3' as default
        run: ./target/debug/quicktest setup config --label="Language::Python.PROGRAM" --value="python3"

      - name: Test cmp command
        run: |
          source ~/.bashrc
          cargo test cmp_subcommand -- --test-threads 1

      - name: Test stress command
        run: |
          source ~/.bashrc
          cargo test stress_subcommand -- --test-threads 1
      
      - name: Test check command
        run: |
          source ~/.bashrc
          cargo test check_subcommand -- --test-threads 1

      - name: Test output command
        run: |
          source ~/.bashrc
          cargo test output_subcommand -- --test-threads 1

      - name: Test setup command
        run: |
          source ~/.bashrc
          cargo test setup_subcommand -- --test-threads 1
